import type { LanguageCode } from '@/shared/constants/curriculum';

/**
 * ABSTENTION IS A FIRST-CLASS ANSWER, NOT AN ERROR.
 *
 * ===========================================================================
 * THE ENTIRE DESIGN IN ONE SENTENCE: "I could not find this in your textbook"
 * is a CORRECT answer, and it is delivered as one.
 *
 * It arrives on a 200, in the ordinary stream, as an `abstention` FRAME rather
 * than an `error` frame, and it is persisted as an ordinary assistant message
 * with `abstained = true`. The client renders it as an answer with no retry
 * button, because retrying will produce the same answer — the textbook does not
 * contain it.
 *
 * The alternative, which almost every RAG system ships by default, is to let the
 * model answer anyway. That produces a fluent, confident, cited-looking
 * paragraph about something the corpus does not cover, and there is no signal
 * anywhere that distinguishes it from a good answer. A tutor that occasionally
 * invents CBSE content is worse than one that occasionally says it does not
 * know, because a child cannot tell which is which and a parent finds out at an
 * exam.
 * ===========================================================================
 *
 * WHY THE REASONS ARE DISTINGUISHED IN THE MESSAGE AT ALL. Retrieval's
 * `AbstainReason` separates "found nothing" from "found only weak matches", and
 * a student can act on that difference: nothing found usually means the question
 * belongs to another subject or another chapter, while a weak match usually
 * means the wording needs to change. Telling them apart is the difference
 * between a dead end and a next step.
 *
 * The two are NOT distinguished in a way that reveals anything about the corpus.
 * "I have nothing on this" and "I found something close but not close enough"
 * are statements about the answer, not about which chapters exist.
 */

/** Mirrors `retrieval`'s `AbstainReason`, plus this module's own two cases. */
export const ABSTENTION_REASONS = [
  /** Retrieval returned no candidates at all. */
  'no_results',
  /** Candidates existed but the top fused score was below the floor. */
  'below_threshold',
  /** The safety classifier refused before anything was retrieved. */
  'refused',
  /** The student has no subjects, or the session's subject is not one of them. */
  'out_of_scope',
] as const;
export type AbstentionReason = (typeof ABSTENTION_REASONS)[number];

export interface BilingualText {
  readonly en: string;
  readonly hi: string;
}

/**
 * The exact sentences. Fixed, bilingual, and identical every time.
 *
 * NOT generated by the model. An abstention produced by asking a model to
 * explain that it cannot answer is (a) a model call we just decided not to make
 * and (b) a sentence that varies. Both of those are the opposite of the point.
 *
 * Every one of them ENDS WITH A NEXT STEP. "I do not know" is honest and
 * useless; a child who is stuck needs to be told what to try. That is the
 * difference between abstention as a product decision and abstention as a
 * failure message.
 */
const ABSTENTION_TEXT: Readonly<Record<AbstentionReason, BilingualText>> = Object.freeze({
  no_results: {
    en:
      'I could not find this in your NCERT textbook for this subject, so I am not going to ' +
      'guess. Check whether it belongs to another subject, or pick the chapter it comes from ' +
      'and ask me again there.',
    hi:
      'यह मुझे इस विषय की तुम्हारी NCERT किताब में नहीं मिला, इसलिए मैं अंदाज़ा नहीं लगाऊँगा। ' +
      'देखो कि यह किसी और विषय का तो नहीं है, या जिस अध्याय से यह है उसे चुनकर मुझसे वहाँ फिर पूछो।',
  },
  below_threshold: {
    en:
      'I found something close to this in your textbook, but not close enough to be sure — and ' +
      'I would rather say so than guess. Try asking it in different words, or name the chapter ' +
      'it comes from.',
    hi:
      'तुम्हारी किताब में मुझे इससे मिलता-जुलता कुछ मिला, पर इतना पक्का नहीं कि मैं भरोसे से कह सकूँ — ' +
      'और अंदाज़ा लगाने से बेहतर है कि मैं यह बता दूँ। इसे अलग शब्दों में पूछो, या अध्याय का नाम बताओ।',
  },
  refused: {
    // Deliberately never reached with this text: the SAFETY refusal carries its
    // own wording (`domain/safety.ts`), which is category-specific and, in the
    // harm case, names a helpline. This exists so the reason set is total and a
    // future caller cannot land on `undefined`.
    en: 'I can only help with your CBSE school subjects. Let us go back to your chapter.',
    hi: 'मैं सिर्फ़ तुम्हारे CBSE स्कूल विषयों में मदद कर सकता हूँ। चलो अपने अध्याय पर वापस चलते हैं।',
  },
  out_of_scope: {
    en:
      'This subject is not on your list yet, so I do not have your textbook for it. Add it in ' +
      'your profile and ask me again.',
    hi:
      'यह विषय अभी तुम्हारी सूची में नहीं है, इसलिए मेरे पास इसकी तुम्हारी किताब नहीं है। ' +
      'इसे अपनी प्रोफ़ाइल में जोड़ो और मुझसे फिर पूछो।',
  },
});

export function abstentionMessage(reason: AbstentionReason, language: LanguageCode): string {
  return ABSTENTION_TEXT[reason][language];
}

export function abstentionMessages(reason: AbstentionReason): BilingualText {
  return ABSTENTION_TEXT[reason];
}

/**
 * Maps retrieval's reason onto this module's.
 *
 * Retrieval's vocabulary is about SEARCH; this one is about what a student is
 * told. They agree today and are still translated rather than shared, because
 * `retrieval` is allowed to add a search reason without that reason
 * automatically becoming a sentence shown to a child.
 *
 * An unrecognised reason maps to `no_results`, which is the SAFER of the two —
 * it tells the student the material was not found, which is true of any
 * abstention, rather than implying a near miss that may not have happened.
 */
export function fromRetrievalReason(reason: string | null): AbstentionReason {
  // `'below-threshold'` is retrieval's spelling, hyphenated. Translating rather
  // than importing the union is the point of this function — see above — and
  // the hyphen is a small reminder that these are two vocabularies.
  return reason === 'below-threshold' ? 'below_threshold' : 'no_results';
}
