import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { listMigrations, migrationsDirFor, type MigrationSet } from '../helpers/postgres';

/**
 * ============================================================================
 * THE JOURNAL'S `when` VALUES MUST BE STRICTLY INCREASING WITH `idx`.
 *
 * This is D-109 as a mechanical rule, and it is the one property of the
 * migration set that NO OTHER TEST IN THE SUITE CAN SEE.
 * ============================================================================
 *
 * WHY NOTHING ELSE CATCHES IT. Every other migration test — the round trip,
 * the snapshot chain, every module's harness — reaches the files through
 * `listMigrations()`, which sorts by `idx`. That is the correct order to APPLY
 * in, and it is why those tests are right to use it. But `drizzle-orm`'s own
 * migrator does not use `idx` at all: it reads the last row of
 * `drizzle.__drizzle_migrations`, takes its `created_at`, and applies only the
 * journal entries whose `when` is GREATER than that number.
 *
 * So a journal whose `when` values are out of order is invisible to a test
 * that applies by `idx`, and fatal to a real deployment. The migrator prints
 * "Migrations applied." and applies nothing — the exact shape D-109 records,
 * and the shape `0004_billing` shipped in: its `when` (1786374108357) sat
 * BELOW `0003_parent`'s (1786700000000), so on any database already past 0003
 * the billing migration was skipped in silence and `subscriptions` and
 * `payment_events` simply never existed. Reproduced against a scratch database
 * before this test was written, and reproduced again by reverting the value
 * afterwards to prove the test fires.
 *
 * THE FAILURE MODE THIS PREVENTS IS NOT "an error". It is a schema that is
 * missing two tables while every command in the deploy pipeline reported
 * success — which is why the rule is checked here, on the FILE, rather than
 * hoped for at review time. Migration `when` values are generated by
 * `drizzle-kit` from the wall clock and hand-edited whenever a migration is
 * renumbered or written by hand, and a hand-edited timestamp is exactly the
 * kind of thing that is right four times and wrong once.
 *
 * Pure: reads two JSON files, starts nothing, connects to nothing.
 */

interface JournalEntry {
  readonly idx: number;
  readonly when: number;
  readonly tag: string;
}

interface Journal {
  readonly entries: readonly JournalEntry[];
}

function readJournal(set: MigrationSet): Journal {
  return JSON.parse(
    readFileSync(resolve(process.cwd(), migrationsDirFor(set), 'meta/_journal.json'), 'utf8'),
  ) as Journal;
}

/** Journal entries in the order the migrator would consider them: by `idx`. */
function entriesByIdx(set: MigrationSet): readonly JournalEntry[] {
  return [...readJournal(set).entries].sort((a, b) => a.idx - b.idx);
}

describe.each<MigrationSet>(['current', 'superseded'])('the %s journal', (set) => {
  it('has a subject at all', () => {
    // A guard on the guard. A moved directory or a renamed journal would make
    // every assertion below pass over an empty array — a green test with no
    // subject, which is the failure `listMigrations` was hardened against and
    // which this file must not reintroduce.
    const entries = entriesByIdx(set);
    expect(entries.length).toBeGreaterThan(0);
    expect(entries.length).toBe(listMigrations(set).length);
  });

  it('carries a finite integer `when` on every entry', () => {
    // A missing or non-numeric `when` is coerced by the migrator rather than
    // rejected, and `undefined > n` is false — so the entry is skipped exactly
    // like an out-of-order one, with no message that says so.
    for (const entry of entriesByIdx(set)) {
      expect({ tag: entry.tag, integer: Number.isSafeInteger(entry.when) }).toEqual({
        tag: entry.tag,
        integer: true,
      });
      expect(entry.when).toBeGreaterThan(0);
    }
  });

  it('increases `when` STRICTLY with `idx`', () => {
    /**
     * THE ASSERTION. Strictly, not merely non-decreasing: two entries sharing
     * a `when` means the second is `>` nothing once the first is recorded, so
     * an equal pair is skipped by the same arithmetic as an inverted one.
     *
     * The failure message names BOTH tags, because the useful fact is which
     * pair is inverted — not that some pair is.
     */
    const entries = entriesByIdx(set);

    for (let position = 1; position < entries.length; position += 1) {
      const previous = entries[position - 1];
      const current = entries[position];
      expect(previous).toBeDefined();
      expect(current).toBeDefined();
      if (previous === undefined || current === undefined) {
        continue;
      }

      expect({
        after: current.tag,
        before: previous.tag,
        increases: current.when > previous.when,
      }).toEqual({ after: current.tag, before: previous.tag, increases: true });
    }
  });

  it('would apply every migration to a database whose ledger is at any earlier entry', () => {
    /**
     * THE SAME RULE, STATED THE WAY THE DEFECT WAS ACTUALLY EXPERIENCED —
     * because "the numbers ascend" is an abstraction and "0004 is skipped on a
     * database already at 0003" is the incident.
     *
     * This is `drizzle-orm`'s selection rule, transcribed: for a ledger whose
     * last recorded `created_at` is entry N's `when`, the migrator applies
     * exactly the entries whose `when` is strictly greater. Every entry after
     * N must therefore survive that filter. A tag missing from the result is a
     * migration that a real deployment would skip while reporting success.
     */
    const entries = entriesByIdx(set);

    for (const applied of entries) {
      const stillPending = entries
        .filter((entry) => entry.when > applied.when)
        .map((entry) => entry.tag);
      const shouldBePending = entries
        .filter((entry) => entry.idx > applied.idx)
        .map((entry) => entry.tag);

      expect({ ledgerAt: applied.tag, pending: stillPending }).toEqual({
        ledgerAt: applied.tag,
        pending: shouldBePending,
      });
    }
  });
});
