-- 0001_link_codes — resolves decision D-012.
--
-- Generated by drizzle-kit, then reviewed by hand (plan §4, rule 1). Two
-- changes were made to the generated output, both comments; no DDL was
-- altered. Read the header, then the two notes inline.
--
-- WHY: link codes lived in `platform/cache` because a code is issued before
-- any parent exists and `parent_child_links.parent_user_id` is NOT NULL. The
-- cache gave "one active code per student" and expiry for free, and gave away
-- durability in exchange: a cache restart silently invalidated every
-- outstanding code, so a parent entering a code their child had just read
-- aloud was told it was invalid. Intermittent, unreproducible, and sitting in
-- the middle of the onboarding funnel.
--
-- THE COLUMN DROP: plan §4, rule 3 says never drop a column in the same
-- release that stops using it. That rule protects a running deployment from a
-- rolling restart where old and new code are live at once. This service has
-- never been deployed, `parent_child_links` is empty everywhere it exists, and
-- `code_expires_at` has no reader once the codes move. Dropping it now is
-- correct here and would NOT be correct after the first production deploy.
-- Recorded as D-023.

CREATE TABLE "link_codes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"student_user_id" uuid NOT NULL,
	"code" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "link_codes" ADD CONSTRAINT "link_codes_student_user_id_users_id_fk" FOREIGN KEY ("student_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- A parent submits a bare 6-character code with no student id, so the code
-- alone has to identify the student. Globally unique, not per-student.
CREATE UNIQUE INDEX "link_codes_code_unique" ON "link_codes" USING btree ("code");--> statement-breakpoint
-- THE PARTIAL UNIQUE INDEX. This is what enforces "one active code per
-- student" (§6.8, step 1) — in the database, not in application logic. Two
-- concurrent issue requests cannot both win, and no future code path can
-- forget the rule. Consumed rows are excluded by the predicate, so the audit
-- history accumulates without ever blocking a new code.
CREATE UNIQUE INDEX "link_codes_one_active_per_student" ON "link_codes" USING btree ("student_user_id") WHERE consumed_at is null;--> statement-breakpoint
CREATE INDEX "link_codes_expires_at_idx" ON "link_codes" USING btree ("expires_at");--> statement-breakpoint
-- `link_code` STAYS on the link row: it is the historical record of which code
-- created the link. Only the expiry goes, because expiry is a property of the
-- code and the code now has a table of its own. Two copies of one lifetime is
-- two things that can disagree.
ALTER TABLE "parent_child_links" DROP COLUMN "code_expires_at";
