-- 0002_learner_content — the `learner` and `content` schemas, plus one
-- `practice` table that could not wait for its module.
--
-- Generated by drizzle-kit, then reviewed by hand (plan §4, rule 1). The hand
-- pass removed one redundant index, added two missing foreign-key indexes, and
-- appended the COMMENT ON COLUMN block at the foot of this file. No generated
-- DDL was otherwise altered.
--
-- ===========================================================================
-- WHAT LANDS HERE
--
--   learner   students · student_subjects · chapter_mastery
--   content   chapters · questions · rag_chunks
--   practice  question_responses  (the module is build step 11; see below)
--
-- All three are assigned the `core` connection pool
-- (04-RESILIENCE-PLAN.md §3.1, declared in src/app/module-pools.ts).
-- `retrieval` and `foxy` will READ rag_chunks on the `ai` pool, which is the
-- entire point of §3.1: a slow vector scan cannot hold a connection that a
-- chapter listing — or a login — needs.
--
-- ===========================================================================
-- GRADES ARE TEXT. "6" to "12", three tables, three CHECK constraints.
--
-- This is plan §3's hard rule made mechanical. The failure it prevents is not
-- a crash: `"6" !== 6` makes a filter match nothing, so an integer grade
-- surfaces as an empty question list for one cohort and reads as missing
-- content rather than as a bug.
--
-- WHAT THE CHECK DOES AND DOES NOT BUY, established by a test after an earlier
-- draft of this header claimed more than was true:
--
--   IT DOES enforce the VALUE domain. "05", "6 ", "Class 6" and "13" are all
--   refused, in every table, on every write path.
--
--   IT DOES NOT enforce the caller's TYPE. `values (6)` with a bare integer
--   literal SUCCEEDS and stores '6' — Postgres has an assignment cast from
--   integer to text and applies it silently. node-postgres arrives at the same
--   place by another road, sending a JavaScript `6` as an untyped parameter
--   that Postgres infers as text.
--
-- The value in the column is therefore always correct, but "grade 6 as a
-- NUMBER is rejected" (§8.2) is a rule ONLY the module's Zod contract can
-- enforce. That contract is the sole barrier between a JSON number and this
-- column; it is not a convenience wrapper and must not be removed on the
-- belief that the CHECK covers it.
--
-- ===========================================================================
-- THE FOUR-OPTION RULE IS A CONSTRAINT, NOT A VALIDATION.
--
-- §8.3 requires a question with other than 4 options to be rejected.
-- Application validation protects the paths that run it; a CHECK protects the
-- paths nobody remembered — the bulk import, the admin fix-up, the psql
-- session at 2am. Paired with `correct_index` 0..3, the index can never point
-- past the end of the array.
--
-- ===========================================================================
-- THE THREE ONE-WAY DOORS (PROGRESS.md §8). Hours now, unrecoverable later.
--
--   questions.distractor_misconceptions
--       WHY the wrong option was tempting. Without it the parent digest can
--       only report percentages, which is what every competitor reports.
--       Retrofitting means a human re-reading the whole question bank.
--   questions.is_held_out
--       Questions reserved for independent mastery checks, never served in
--       practice. A question that has been served is contaminated forever;
--       you cannot un-serve it. The reserve has to exist before the first
--       student sees the bank.
--   question_responses
--       Every answer, with the difficulty AS AUTHORED AT THE TIME. Real
--       difficulty is only computable from responses recorded when they
--       happened. There is no way to reconstruct them later, so the table
--       lands three build steps ahead of the module that owns it.
--
-- ===========================================================================
-- rag_chunks IS SHAPED FOR AN IMPORT, NOT FOR ELEGANCE.
--
-- It is populated by a one-time copy from the existing production table
-- `rag_content_chunks` (~16,000 rows). Every column that exists in both keeps
-- the SOURCE name, type and default, so the import is a column mapping rather
-- than a transform — a transform step is a place for 16,000 rows to be
-- quietly corrupted. `embedding` is vector(1024) because that is exactly what
-- voyage-3 produced for the existing corpus; changing the width invalidates
-- every stored vector and turns a copy into a paid re-embedding run.
--
-- Two deliberate departures the import script must know about:
--   * `chapter_id` is NEW and NULLABLE. Import leaves it null; a backfill
--     joins (grade, subject, chapter_number) to `chapters`. It stays nullable
--     forever — a chunk whose chapter is not in the syllabus table is still
--     retrievable content and must not be lost to a NOT NULL.
--   * `search_vector` is GENERATED ALWAYS ... STORED. DO NOT MAP IT. This is
--     the one place the straight mapping is broken on purpose: a
--     hand-maintained tsvector goes stale the first time someone edits
--     chunk_text and forgets, and a stale tsvector does not fail — the chunk
--     simply stops appearing in keyword search, forever, silently.
--
-- Pre-flight before the import, because `grade` carries the "6".."12" CHECK:
--     select distinct grade from rag_content_chunks;
-- A row outside that range is unreachable content (retrieval hard-filters by
-- grade, §8.4 step 3), so failing loudly on it is the correct outcome — but
-- discovering it at 2am mid-import is not. `language` deliberately carries NO
-- check for the same reason inverted: grade is a product invariant, language
-- is a label, and an unexpected 'en-IN' must not block the import.
--
-- ===========================================================================
-- THE HNSW PARAMETERS: m = 16, ef_construction = 128.
--
-- m = 16 is pgvector's default and is ample graph connectivity at this corpus
-- size; raising it costs memory in every query for recall this corpus does not
-- need. ef_construction is DOUBLED from the default 64 because build cost on
-- 16,000 rows is measured in seconds — a one-time cost that is effectively
-- free — while the recall it buys is permanent and cannot be added later
-- without a rebuild.
--
-- Build-time and query-time settings that are NOT in this file because they
-- are session GUCs, and that the import script and the retrieval module
-- respectively must set:
--
--   set maintenance_work_mem = '512MB';   -- before the index build. 16,000 ×
--       1024 × 4 bytes is ~65 MB of vectors; if the graph does not fit,
--       pgvector builds on disk and takes far longer for a worse graph.
--   set hnsw.ef_search = 100;             -- retrieval takes the TOP 50
--       (§8.4 step 3). pgvector's default ef_search is 40, which is BELOW 50,
--       and an HNSW scan will not return more rows than ef_search.
--
--       MEASURED on pgvector 0.8.6, 180 seeded rows, HNSW plan forced:
--           ef_search = 40,  limit 50  ->  40 rows
--           ef_search = 100, limit 50  ->  50 rows
--       Left at the default, retrieval silently receives 40 candidates where
--       it asked for 50. That reads as "the corpus is thin", not as a
--       misconfiguration, which is exactly why it is written down here.
--
-- AND THE ONE THAT WILL BITE: §8.4 hard-filters by grade and subject. An HNSW
-- search walks the graph over the WHOLE table and filters afterwards, so a
-- narrow filter — ~380 rows per (grade, subject) partition at 16,000 rows —
-- can return far fewer than 50 results while looking like a successful query.
-- Set `hnsw.iterative_scan = relaxed_order` (pgvector 0.8+; the container
-- ships 0.8.6, so it is available).
--
-- ALSO MEASURED, and reassuring: at seed scale the planner does NOT choose
-- HNSW for a filtered query at all — it takes a bitmap scan on
-- rag_chunks_grade_subject_idx and sorts exactly. That is the right choice and
-- has perfect recall. It also means the HNSW path is effectively UNTESTED by
-- any small-corpus query, so the filtered-recall behaviour above must be
-- re-measured against the real 16,000-row corpus before the abstention
-- threshold is calibrated. Do not carry these numbers forward as if they
-- settled it.
--
-- The HNSW index is NOT partial, unlike the (grade, subject) filter index.
-- A partial index is unusable by a query that omits its predicate, and the
-- fallback for the vector index is a sequential scan over every embedding —
-- which against the `ai` pool's 5s statement timeout reads as an outage. The
-- filter index can afford that fallback; this one cannot.
-- ===========================================================================

CREATE TABLE "chapter_mastery" (
	"student_user_id" uuid NOT NULL,
	"chapter_id" uuid NOT NULL,
	"mastery_score" numeric(4, 3) DEFAULT '0' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_practised_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chapter_mastery_pkey" PRIMARY KEY("student_user_id","chapter_id"),
	CONSTRAINT "chapter_mastery_score_check" CHECK ("chapter_mastery"."mastery_score" >= 0 and "chapter_mastery"."mastery_score" <= 1),
	CONSTRAINT "chapter_mastery_attempts_check" CHECK ("chapter_mastery"."attempts" >= 0)
);
--> statement-breakpoint
CREATE TABLE "student_subjects" (
	"student_user_id" uuid NOT NULL,
	"subject_code" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "student_subjects_pkey" PRIMARY KEY("student_user_id","subject_code"),
	CONSTRAINT "student_subjects_subject_code_check" CHECK (length(btrim("student_subjects"."subject_code")) > 0)
);
--> statement-breakpoint
CREATE TABLE "students" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"display_name" text NOT NULL,
	"grade" text NOT NULL,
	"board" text DEFAULT 'CBSE' NOT NULL,
	"preferred_language" text DEFAULT 'en' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "students_grade_check" CHECK ("students"."grade" in ('6', '7', '8', '9', '10', '11', '12')),
	CONSTRAINT "students_preferred_language_check" CHECK ("students"."preferred_language" in ('en', 'hi')),
	CONSTRAINT "students_display_name_check" CHECK (length(btrim("students"."display_name")) > 0)
);
--> statement-breakpoint
CREATE TABLE "chapters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"grade" text NOT NULL,
	"subject_code" text NOT NULL,
	"chapter_number" integer NOT NULL,
	"title_en" text NOT NULL,
	"title_hi" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chapters_grade_check" CHECK ("chapters"."grade" in ('6', '7', '8', '9', '10', '11', '12')),
	CONSTRAINT "chapters_chapter_number_check" CHECK ("chapters"."chapter_number" > 0),
	CONSTRAINT "chapters_title_en_check" CHECK (length(btrim("chapters"."title_en")) > 0)
);
--> statement-breakpoint
CREATE TABLE "questions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"chapter_id" uuid NOT NULL,
	"question_text" text NOT NULL,
	"options" jsonb NOT NULL,
	"correct_index" integer NOT NULL,
	"explanation" text NOT NULL,
	"difficulty" text NOT NULL,
	"bloom_level" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"distractor_misconceptions" jsonb,
	"is_held_out" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "questions_options_check" CHECK (case when jsonb_typeof("questions"."options") = 'array'
                then jsonb_array_length("questions"."options") = 4
                 and jsonb_array_length("questions"."options" - '') = 4
                else false
           end),
	CONSTRAINT "questions_correct_index_check" CHECK ("questions"."correct_index" >= 0 and "questions"."correct_index" < 4),
	CONSTRAINT "questions_question_text_check" CHECK (length(btrim("questions"."question_text")) > 0),
	CONSTRAINT "questions_explanation_check" CHECK (length(btrim("questions"."explanation")) > 0),
	CONSTRAINT "questions_difficulty_check" CHECK ("questions"."difficulty" in ('easy', 'medium', 'hard')),
	CONSTRAINT "questions_bloom_level_check" CHECK ("questions"."bloom_level" in ('remember', 'understand', 'apply', 'analyse', 'evaluate', 'create')),
	CONSTRAINT "questions_distractor_misconceptions_check" CHECK ("questions"."distractor_misconceptions" is null
          or case when jsonb_typeof("questions"."distractor_misconceptions") = 'array'
                  then jsonb_array_length("questions"."distractor_misconceptions") = 3
                  else false
             end)
);
--> statement-breakpoint
CREATE TABLE "rag_chunks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"chapter_id" uuid,
	"chunk_text" text NOT NULL,
	"chunk_index" integer DEFAULT 0 NOT NULL,
	"chunk_type" text DEFAULT 'paragraph' NOT NULL,
	"board" text DEFAULT 'CBSE' NOT NULL,
	"grade" text NOT NULL,
	"subject" text NOT NULL,
	"chapter_number" integer,
	"chapter_title" text,
	"topic" text,
	"concept" text,
	"difficulty_level" integer DEFAULT 2,
	"content_layer" text DEFAULT 'foundation',
	"language" text DEFAULT 'en',
	"embedding" vector(1024),
	"embedding_model" text,
	"embedded_at" timestamp with time zone,
	"word_count" integer,
	"token_count" integer,
	"quality_score" double precision,
	"is_active" boolean DEFAULT true NOT NULL,
	"search_vector" "tsvector" GENERATED ALWAYS AS (case when language = 'hi'
            then setweight(to_tsvector('simple', coalesce(chapter_title, '') || ' ' || coalesce(topic, '') || ' ' || coalesce(concept, '')), 'A')
              || setweight(to_tsvector('simple', coalesce(chunk_text, '')), 'B')
            else setweight(to_tsvector('english', coalesce(chapter_title, '') || ' ' || coalesce(topic, '') || ' ' || coalesce(concept, '')), 'A')
              || setweight(to_tsvector('english', coalesce(chunk_text, '')), 'B')
          end) STORED,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "rag_chunks_grade_check" CHECK ("rag_chunks"."grade" in ('6', '7', '8', '9', '10', '11', '12')),
	CONSTRAINT "rag_chunks_chunk_text_check" CHECK (length(btrim("rag_chunks"."chunk_text")) > 0),
	CONSTRAINT "rag_chunks_chunk_index_check" CHECK ("rag_chunks"."chunk_index" >= 0)
);
--> statement-breakpoint
CREATE TABLE "question_responses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"student_user_id" uuid NOT NULL,
	"question_id" uuid NOT NULL,
	"selected_index" integer NOT NULL,
	"is_correct" boolean NOT NULL,
	"time_spent_ms" integer NOT NULL,
	"authored_difficulty" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "question_responses_selected_index_check" CHECK ("question_responses"."selected_index" >= 0 and "question_responses"."selected_index" < 4),
	CONSTRAINT "question_responses_time_spent_check" CHECK ("question_responses"."time_spent_ms" >= 0),
	CONSTRAINT "question_responses_authored_difficulty_check" CHECK ("question_responses"."authored_difficulty" in ('easy', 'medium', 'hard'))
);
--> statement-breakpoint
ALTER TABLE "chapter_mastery" ADD CONSTRAINT "chapter_mastery_student_user_id_students_user_id_fk" FOREIGN KEY ("student_user_id") REFERENCES "public"."students"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chapter_mastery" ADD CONSTRAINT "chapter_mastery_chapter_id_chapters_id_fk" FOREIGN KEY ("chapter_id") REFERENCES "public"."chapters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_subjects" ADD CONSTRAINT "student_subjects_student_user_id_students_user_id_fk" FOREIGN KEY ("student_user_id") REFERENCES "public"."students"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "students" ADD CONSTRAINT "students_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questions" ADD CONSTRAINT "questions_chapter_id_chapters_id_fk" FOREIGN KEY ("chapter_id") REFERENCES "public"."chapters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rag_chunks" ADD CONSTRAINT "rag_chunks_chapter_id_chapters_id_fk" FOREIGN KEY ("chapter_id") REFERENCES "public"."chapters"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "question_responses" ADD CONSTRAINT "question_responses_student_user_id_students_user_id_fk" FOREIGN KEY ("student_user_id") REFERENCES "public"."students"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "question_responses" ADD CONSTRAINT "question_responses_question_id_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "chapter_mastery_chapter_idx" ON "chapter_mastery" USING btree ("chapter_id");--> statement-breakpoint
CREATE UNIQUE INDEX "chapters_grade_subject_number_unique" ON "chapters" USING btree ("grade","subject_code","chapter_number");--> statement-breakpoint
CREATE INDEX "questions_chapter_active_held_out_idx" ON "questions" USING btree ("chapter_id","is_active","is_held_out");--> statement-breakpoint
CREATE INDEX "rag_chunks_embedding_hnsw" ON "rag_chunks" USING hnsw ("embedding" vector_cosine_ops) WITH (m=16,ef_construction=128);--> statement-breakpoint
CREATE INDEX "rag_chunks_search_vector_gin" ON "rag_chunks" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "rag_chunks_grade_subject_idx" ON "rag_chunks" USING btree ("grade","subject") WHERE is_active;--> statement-breakpoint
CREATE INDEX "rag_chunks_chapter_idx" ON "rag_chunks" USING btree ("chapter_id");--> statement-breakpoint
CREATE INDEX "question_responses_question_idx" ON "question_responses" USING btree ("question_id","created_at");--> statement-breakpoint
CREATE INDEX "question_responses_student_idx" ON "question_responses" USING btree ("student_user_id","created_at" DESC NULLS LAST);
--> statement-breakpoint
-- ===========================================================================
-- COMMENT ON COLUMN — the rules that must survive this file.
--
-- A comment in the schema source is invisible to anyone holding a psql
-- prompt, and these are exactly the rules somebody will need at that moment.
-- ===========================================================================
COMMENT ON COLUMN "questions"."distractor_misconceptions" IS
  'Three misconception codes, one per WRONG option. ALIGNMENT: ordered by option index ASCENDING, SKIPPING correct_index. With correct_index=1, element 0 describes option 0, element 1 describes option 2, element 2 describes option 3. Getting this wrong mislabels every misconception silently. NULL until authored.';--> statement-breakpoint
COMMENT ON COLUMN "questions"."is_held_out" IS
  'TRUE = reserved for independent mastery checks. MUST NEVER be served in practice: a question that has been practised may have been memorised and can no longer measure anything. Contamination is irreversible.';--> statement-breakpoint
COMMENT ON COLUMN "question_responses"."authored_difficulty" IS
  'The difficulty the question carried WHEN IT WAS SERVED. Denormalised on purpose - joining questions.difficulty instead would let a later correction retroactively rewrite history, destroying the calibration this table exists for.';--> statement-breakpoint
COMMENT ON COLUMN "rag_chunks"."search_vector" IS
  'GENERATED ALWAYS ... STORED. Never write to it; the corpus import must NOT map the source column of the same name.';--> statement-breakpoint
COMMENT ON COLUMN "rag_chunks"."embedding" IS
  'voyage-3, 1024 dimensions. The width matches the existing corpus exactly, which is what makes the import a copy rather than a paid re-embedding run.';
