-- 0003_misconception_object — `questions.distractor_misconceptions` becomes a
-- jsonb OBJECT keyed by option index, replacing the positional array.
--
-- Generated by drizzle-kit, then reviewed by hand (plan §4, rule 1). The hand
-- pass appended this header and the COMMENT ON COLUMN at the foot; the
-- generated DDL is unaltered.
--
-- ===========================================================================
-- WHY, AND WHY NOW.
--
-- Migration 0002 shipped the column as a jsonb ARRAY of three codes aligned to
-- the three wrong options: option index ascending, SKIPPING correct_index.
-- D-044 implemented that as specified and flagged it in the same breath.
--
-- THE FAILURE THE ARRAY SHAPE ALLOWS. Alignment is a rule held OUTSIDE the
-- data, in a comment. Reorder the options — a content edit nobody would think
-- to treat as dangerous — and every code now describes a different option.
-- Correct `correct_index` from 1 to 2, and the three codes shift by one. In
-- both cases NOTHING ERRORS. There is no constraint to violate, no type to
-- mismatch, no row count to change. The only visible effect is that the weekly
-- parent digest starts saying "she is confusing mass with weight" about a
-- child who is doing nothing of the kind — and the misconception sentence is
-- the whole reason this product is not a percentage dashboard.
--
-- THE OBJECT SHAPE REMOVES IT ENTIRELY, because the alignment becomes a
-- property of the value rather than of a convention:
--
--     {"0": "confuses_mass_weight", "2": "unit_conversion_step", "3": "sign_error_negative"}
--
-- Keys are option indexes as text. The key equal to `correct_index` is ABSENT:
-- the correct option has no misconception to describe.
--
-- NOW, because the question bank is not authored yet. There are ZERO rows in
-- `questions` in any environment, so this migration rewrites nothing and needs
-- no backfill. Once the bank exists, the same change costs a data migration
-- that has to infer, per question, which option each positional code meant —
-- and any question whose options were EVER reordered can no longer be inferred
-- at all. Cheap today, unrecoverable later. That is the definition of a
-- one-way door, and this is the last moment it is free.
--
-- ===========================================================================
-- WHAT THE CONSTRAINT ENFORCES, and why it is written this way.
--
--   1. exactly three entries;
--   2. every key is an option index, "0".."3";
--   3. the key equal to `correct_index` is ABSENT.
--
-- Rule 3 is what earns the change. It converts the silent corruption above
-- into a loud rejection: correcting `correct_index` on a question whose codes
-- were authored for the previous answer now FAILS, and the author is forced to
-- correct the codes with it.
--
-- The CASE is not stylistic. Postgres does not guarantee the evaluation order
-- of `AND` (see the header of 0002 and D-039), so a non-object value has to be
-- refused by a branch rather than by an operand that merely happens to run
-- second — otherwise `{"a":1}` raises a raw type error instead of naming this
-- constraint.
--
-- The operator choice is forced by one restriction: a CHECK may not contain a
-- subquery. That rules out `jsonb_object_keys` (set-returning) and every
-- aggregate. So:
--   entry count  jsonb_path_query_array(x, '$.keyvalue()') is a plain
--                IMMUTABLE scalar function returning one array element per
--                entry, so its length is the count.
--   legal keys   `jsonb - text[]` deletes all four legal keys at once; an
--                empty remainder proves nothing else was present.
--   correct key  `?` tests a single key.
--
-- NULL remains legal. The codes are authored later, and absent is honest where
-- a row of placeholders would be a silent claim to have diagnosed something.
-- ===========================================================================

ALTER TABLE "questions" DROP CONSTRAINT "questions_distractor_misconceptions_check";--> statement-breakpoint
ALTER TABLE "questions" ADD CONSTRAINT "questions_distractor_misconceptions_check" CHECK (case
            when "questions"."distractor_misconceptions" is null then true
            when jsonb_typeof("questions"."distractor_misconceptions") <> 'object' then false
            else jsonb_array_length(
                   jsonb_path_query_array("questions"."distractor_misconceptions", '$.keyvalue()')
                 ) = 3
                 and "questions"."distractor_misconceptions" - array['0', '1', '2', '3'] = '{}'::jsonb
                 and not ("questions"."distractor_misconceptions" ? ("questions"."correct_index")::text)
          end);--> statement-breakpoint
-- ===========================================================================
-- The column comment is REPLACED, not amended. It described the positional
-- alignment rule, and a stale comment on this particular column is worse than
-- none: the person reading it is at a psql prompt about to hand-author codes.
-- ===========================================================================
COMMENT ON COLUMN "questions"."distractor_misconceptions" IS
  'Misconception codes as a jsonb OBJECT KEYED BY OPTION INDEX, e.g. {"0":"confuses_mass_weight","2":"unit_conversion_step","3":"sign_error_negative"}. Exactly 3 entries; every key in "0".."3"; the key equal to correct_index is ABSENT (a correct option has no misconception). Keyed rather than positional so that reordering options cannot silently re-label every code - see migration 0003 and D-048. NULL until authored.';
